name: Validate

on:
  push:
    branches:
      - 'main'
  workflow_call:

concurrency:
  group: validate-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CAIDO_NODE_VERSION: 20
  CAIDO_PNPM_VERSION: 9

jobs:
  typecheck:
    name: 'Typecheck'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CAIDO_NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: ${{ env.CAIDO_PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: Run typechecker
        run: pnpm typecheck

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CAIDO_NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: ${{ env.CAIDO_PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint